vich_uploader:
    db_driver: orm

    mappings:
        candidate_image:
            uri_prefix: /images/candidates
            upload_destination: '%kernel.project_dir%/public/images/candidates'
            namer: Vich\UploaderBundle\Naming\Base64Namer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
